### ISSUE TITLE
CSS Grid with tables

### ISSUE THREAD

**Issue by BrianWalters** [rachelandrew/cssgrid-ama#1]
Styling HTML tables are a pain and always have been. I've tried to use flexbox but it doesn't quite work for all use cases. The user agent table styles/behavior are full of gotchas. Is grid finally the answer we're looking for? Can you give us some insight to styling tables with grid?

**Comment by rachelandrew** [comment]
What aren't you able to currently style in a table? There is no reason you can't use grid layout on table elements, but I'm not sure what the use case is you are trying to solve is.

I've played around with the idea of using Grid Layout for "responsive tables" [here](https://rachelandrew.co.uk/archives/2016/03/02/a-grid-solution-for-the-responsive-tables-problem/).

**Comment by BrianWalters** [comment]
Thank you for keeping this issue open. Here's a codepen of a typical table I try to style all the time:
https://codepen.io/Blargon/pen/aBEYJb

I want to have "auto" relationships in my tracks while also setting some tracks to be in frs or exact distances. I've tried to do this with flexbox, but the relationships don't carry across to table rows. I haven't been able to achieve this while also making it semantic and accessible.

**Comment by rachelandrew** [comment]
I'm still unsure why you aren't using the CSS designed for tables for this. What *can't* you do using the CSS designed for tables?
