### ISSUE TITLE
It is it possible to animate css grid properties?

### ISSUE THREAD

**Issue by matthewp** [rachelandrew/cssgrid-ama#10]
And is a good idea to do so? I know that you can animate flexbox (also don't know if that's good idea or not).  Thanks!

**Comment by rachelandrew** [comment]
You can animate the tracks sizing and gaps as shown in [this table](https://www.w3.org/TR/2016/CR-css-grid-1-20160929/#property-index) in the specification. I don't see any reason _not_ to do that. What you can't do is animate the position of an item around the grid.
