### ISSUE TITLE
A question abount 'not building grid framework because css grid is a grid framework'

### ISSUE THREAD

**Issue by rekna1** [rachelandrew/cssgrid-ama#102]
I would like to have your opinion on the following:

In one of your video's you say people should not build grid frameworks with css grid because css grid IS a grid framework. I tried using css grid to build response forms like bootstrap (e.g. where on small screens labels are on top of input's and take full width). 

This is really simple to implement for one form, but when you have multiple forms, do you consider it best practise to define a css grid for each indivual case ?

I have a feeling this will become very repetitive and in the end a lot of css especially with the additional media queries for different screen sizes. Or would in this case a bootstrap like generic grid system be appropriate ?

As a side note: since internet explorer 11 will not be updated to the latest grid specification, will it not burden the success and adoption of CSS grid ? Isn't there any way to encourage MS to update IE11 as well. I don't see Edge becoming the main MS browser soon.

Edge usage is currently less than half of IE11 usage depending on which source you use. For enterprise web applications the figure might even be worse (in the case of the customers of the company I work at, it definitely is worse).

CSS grid has the potential to greatly reduce development time, but if one has to spend time on writing additional css for IE11 that advantage is lost. Especially because often the things which are easy to accomplish with CSS grid are hard to do without CSS grid.  It might also add a lot of complexity to the otherwise clean html.

**Comment by rachelandrew** [comment]
I can't give an opinion about your individual use case. Learning the various technologies puts you in a position to be able to make that call for your project.
