### ISSUE TITLE
How to offset an element without know the exact position.

### ISSUE THREAD

**Issue by lukasoppermann** [rachelandrew/cssgrid-ama#104]
Hey @rachelandrew,

first let me thank you for offering to help people with the css grid layout, it is super helpful when one has the chance to get the help of an expert such as yourself. 👍 

I did not find an answer on the internet nor in the issues here, I hope I did not miss it.

I would like to offset an item, e.g. like this:

```html
[  1  ][  2  ][  3  ]
[  4  ]       [  5  ]
```

However I can't find a way to do it. I tried a `margin-left: 1fr;` but this does not work. Basically I want to be able to tell an item to fill 3 columns but be offset for e.g. 2 columns (2fr). However I because I want to keep it flexible I don't know the exact columns so I can not say start from column 3 and end at column 6. I would like to say: `span 3` and somehow `offset 2`.

I hope my question is understandable? If not, please let me know. Thanks.

**Comment by GJG** [comment]
You could use:   grid-template-areas:
"one"  "two"    " three"
"four"  "empty" "five";

**Comment by lukasoppermann** [comment]
No sorry, I guess my explanation was not good enough. Lets say I have a 12 column grid (however, by changing as css variable this could also be a 16 column grid, etc.) and I want the 3rd item to have an offset of 1 column, no matter if it is in row one at the end or in row two in the middle. I basically have no knowledge of where and in what areas the column is. 

I am trying to build an abstraction in a web component, so I don't know how it will be used. In the end I want to just tell an item it has an offset of 1 and it should have it, no matter where it is.

**Comment by IOIIOOIO** [comment]
@lukasoppermann 

Perhaps you could use Javascript to look for the class eg: "offset-1" and it will add a DOM element with a class of "grid-placeholder" that spans 1 column before your component. Then for "offset-2" it would add 2 elements (or one element that spans 2 columns - but I think it would be easier to abstract if you only have one element that takes up a single column).

I have an implementation idea where I used placeholder elements here:

https://codepen.io/IOIIOOIO/pen/NbrQQr

EDIT: Ah... actually nevermind I just realised with my method you could sometimes end up with something like this...

![placeholder-hack](https://user-images.githubusercontent.com/10476760/31074594-a74b6a14-a771-11e7-9e63-928da81bf85b.png)

**Comment by lukasoppermann** [comment]
Hmm, this is a possibility. But so there is no native support for offsets?
