### ISSUE TITLE
CSS Grid and php & mysql database

### ISSUE THREAD

**Issue by jperson19468** [rachelandrew/cssgrid-ama#106]
I am trying to combine css gride and php & mysql database
Could you please either point me to some websites that have examples and or information on this or better yet do you know of  other forums or groups where I can get help from?

Thanks

**Comment by Kout** [comment]
I’m afraid, you are mixing pears and apples here. CSS grid you use in [frontend development](https://en.wikipedia.org/wiki/Front-end_web_development), while PHP+MySQL are backend technologies. 

Maybe start with this article: http://blog.teamtreehouse.com/i-dont-speak-your-language-frontend-vs-backend or [in Wikipedia](https://en.wikipedia.org/wiki/Front_and_back_ends) to get better orientation.

**Comment by rachelandrew** [comment]
As @Kout has explained, this isn't a grid question.

**Comment by jperson19468** [comment]
Let me be more clear I am getting information from a database using php & mysql. I want to put it into a form or a report on a screen. I want to format the output using CSS grid 
Could you please either point me to some websites that have examples and or information on this or better yet do you know of other forums or groups where I can get help from?
