### ISSUE TITLE
Input shrinks when taken out of focus or typed on in Chrome 61

### ISSUE THREAD

**Issue by FossPrime** [rachelandrew/cssgrid-ama#107]
I was able to reproduce it on codepen MacOS Sierra Chrome 61, in codepen it will only occur on debug view
demo: https://s.codepen.io/fossprime/debug/jGqqXN/yYAyLDzQegzr
code: https://codepen.io/fossprime/pen/jGqqXN

![weird input field](https://user-images.githubusercontent.com/876076/30600265-9889dce2-9d24-11e7-8147-1661c49a72d4.gif)
real world example with vue: https://s.codepen.io/fossprime/debug/pWyveL/DqADdEwPGyjA
code: https://codepen.io/fossprime/pen/pWyveL

UPDATE: Only happens when input has placeholder text
UPDATE 2: doesn't happen on firefox 55
Update 3: does not happen on Windows Chrome 61

**Comment by rachelandrew** [comment]
It's a known bug: https://github.com/rachelandrew/gridbugs#11-a-textarea-that-is-a-grid-item-collapses-to-zero-width

**Comment by FossPrime** [comment]
@rachelandrew  Didn't see it as I found the bug on text inputs. It also collapses when taken out of focus in some cases.

**Comment by FossPrime** [comment]
fixed in Version 63.0.3239.132 (Official Build) (64-bit)
