### ISSUE TITLE
Re: CSS Grid and php & mysql database 

### ISSUE THREAD

**Issue by jperson19468** [rachelandrew/cssgrid-ama#108]
I am trying to combine css gride and php & mysql database
Let me be more clear I am getting information from a database using php & mysql. I want to put it into a form or a report on a screen. I want to format the output using CSS grid
Could you please either point me to some websites that have examples and or information on this or better yet do you know of other forums or groups where I can get help from?

**Comment by rachelandrew** [comment]
This is not the place to ask general web development questions.
