### ISSUE TITLE
Planning UIs that will use CSS Grid

### ISSUE THREAD

**Issue by benthinkin** [rachelandrew/cssgrid-ama#11]
As I understand it, Grid provides both horizontal and vertical alignment of containers in a given space. Before jumping into code, how should UI designers lay out elements to take advantage of CSS Grid in the lo-fi or hi-fi stages of design? Seems like good ol’ table-based layout principles would apply here.

**Comment by rachelandrew** [comment]
Designers will need to understand the constraints and the new opportunities posed by Grid (or any new layout methods) which seems obvious so I don't think I understand the question!

**Comment by deniscarroll** [comment]
If you want to understand more about grids for visual designers you might think about getting a copy of "Grid Systems in Graphic Design/Raster Systeme Fur Die Visuele Gestaltung" https://www.amazon.co.uk/Grid-Systems-Graphic-Design-Communication/dp/3721201450/ref=sr_1_1?s=books&ie=UTF8&qid=1481988857&sr=1-1

As a Graphic Designer myself, the new CSS Grid Layout module (along with Flex) is an absolute winning combination. Once you are working on a grid, you are starting off your design on a rock solid foundation. Only good (layout design - that will compliment your visual assets - typography, images etc) will come from it.

One of it's highlights for me is the new layering opportunities [6.5. Z-axis Ordering: the z-index property](https://www.w3.org/TR/css-grid-1/#z-order).
I can't wait to see the other layouts designers/developers (more likely developer/designers as their experience will accelerate the iterations during experimentation) will dream up with this property alone. All sorts - stuff I couldn't even imagine at this stage. This type of layered layout in a static medium such as books, magazines (and some websites) is one thing - but adding for example, some JavaScript to this is going to be very interesting.

Hopefully white space will  be used (more often) as a design element within webSite design, as it seems to be very *easy to implement now (*as in with the grid + flex there is very fine control over space).

Thanks a million too Rachel for all the great info on your website and especially for the videos you have been making and putting on there during the past few weeks. You have gone above and beyond with helping us learn this new module release, and It is very very much appreciated.

**Comment by benthinkin** [comment]
@rachelandrew Haha, it appears I phrased a vague question poorly. I’m trying to wrap my head around how CSS Grid will change the way designers develop UIs as opposed to using floats and clears. But maybe I need to play with it more myself. And like @deniscarroll said, thank you for providing so many resources, including this AMA.

@deniscarroll Thanks for your insight. Sounds like I’m underestimating Grid’s capabilities. Right now I want to understand what layout differences it gives designers over today’s layout methods … but I think I’m asking the wrong questions.

**Comment by rachelandrew** [comment]
Yes I think the first thing to do is understand the spec, and do some of your own experiments in terms of what is possible.
