### ISSUE TITLE
Grid and Google AMP?

### ISSUE THREAD

**Issue by livlab** [rachelandrew/cssgrid-ama#111]
`TL,DR: ` Are there any specific concerns in using CSS Grid in a Google AMP context?

### Context 1
AMP pages are a significant driver of traffic in the journalism industry since its inception and this continues to grow. Many news orgs can barely afford to have the sites their users need, but are spending money on 3rd parties to maintain separate AMP pages. Thinking about the future of local news sites in similar situation, I'm trying to solve for AMP as much as possible.

### Context 2
News (and most of all other content) layout design has been stagnant since forever. Jen Simmons put is so well[ in this presentation](https://vimeo.com/147950924). In trying to equip small newsrooms with the right UI tools that support their storytelling needs; this is largely translated as layout options that match the types of stories and their content variety. CSS Grid is very promising in this context and I barely scratched the surface exploring what it can do.

## The problem
However far I can push layout differentiation with a CSS Grid implementation, I must also ensure the  AMP 'translation' will not be completely broken and/or at least not a large burden/rework to be satisfactory. 

**Are there concrete things I should keep in mind as I take these competing forces into account?**

**Comment by rachelandrew** [comment]
I don't know anything specific about AMP, there isn't any mention of it here https://www.ampproject.org/docs/guides/responsive/style_pages

You might be better to ask the question in an AMP forum https://www.ampproject.org/support/developer/
