### ISSUE TITLE
Design systems & CSS Grid

### ISSUE THREAD

**Issue by benthinkin** [rachelandrew/cssgrid-ama#12]
Seems like CSS Grid work well with design systems like [Brad Frost’s Atomic Design principles](http://atomicdesign.bradfrost.com/). Do you think designers who build _parts_ before the _whole_ consider Grid-based layouts as they craft elements?

**Comment by rachelandrew** [comment]
It sounds like you are considering using grid layout only for the main layout, I think there are as many use cases for components. The current talk I'm giving at An Event Apart is all about using Grid to develop components, and then using those in a design, I think grid fits very nicely into design systems in that way.

**Comment by benthinkin** [comment]
Thanks for your insight, Rachel. You’re right, I’m approaching it from a broad layout perspective, though perhaps that should change. See, I’m writing a blog post for UI designers: why non-coders should care about Grid … and how they should design for it without annoying front-end developers.

Can you elaborate on developing components with Grid, or is there a better venue to learn about that?

Not sure that I can attend your events, but I look forward to reading more from your books & blog.

**Comment by rachelandrew** [comment]
The best way to approach it is to build some common components yourself using grid layout. I would have thought you would need to do that in order to be able to write a post helping other people do the same. That's essentially how I start every article or talk I write - by building the examples I'll use.
