### ISSUE TITLE
subgrid use case: complex scroll-tables

### ISSUE THREAD

**Issue by justinfagnani** [rachelandrew/cssgrid-ama#121]
I saw your call for use cases here: https://rachelandrew.co.uk/archives/2017/03/16/subgrid-moved-to-level-2-of-the-css-grid-specification/

I think I have one that's not quite captured yet, and I _think_ really needs subgrid to be done properly.

I'm just learning about CSS grid, in the context of the currently impossible to implement without a ton of script, scroll table widget. This is a table with potentially frozen rows and columns at the edges (at the limit resulting in a 9-grid of table sections), where the main section of the table can scroll, and it's scroll position is linked to the scroll position of the frozen rows/cols. Basically the spreadsheet table.

It looks like this is doable with subgrid: define one grid for the table, the for each of the up-to-9 sections, set its start and end row and col and `display: subgrid`. Synchronizing scroll positions would still have to be done in script. I believe `display: contents` does not help because you couldn't style the section as `overflow: auto/scroll`.

Sorry for a lack of pictures for now, but I thought the case might be common/clear enough for you to verify whether this requires subgrid, and is solved by it. Thanks!

**Comment by vilkatis** [comment]
I second this issue that I think might be solved by subgrid. Basically having a table with a fixed header so that I can scroll the table and still see the names of the columns

**Comment by rachelandrew** [comment]
If your data is a table then you need to be using table markup, not sets of divs to represent it.

**Comment by RussellBishop** [comment]
Position: sticky?
