### ISSUE TITLE
Grid gap: why doesn't flexbox have something similar?

### ISSUE THREAD

**Issue by OliverJAsh** [rachelandrew/cssgrid-ama#14]
Hi Rachel,

I am wondering why flexbox doesn't have a property similar to `grid-gap`. It would be useful to define gutters for both axis, as it is possible for a flexbox to wrap.

Currently this requires the use of margins along with negative margin hacks on the parent. I don't see why `grid-gap` (besides the name) couldn't be retrofitted for use with flexbox, as they seem like very similar problems. Forgive my ignorance!

Thanks,
Oliver

**Comment by rachelandrew** [comment]
There has been discussion about this on the mailing list (pre CSS WG moving to GitHub). I linked that discussion up in that issue https://github.com/w3c/csswg-drafts/issues/592

So, yes. I agree it would be nice to have similar gaps in flexbox. So hopefully that will happen!

**Comment by OliverJAsh** [comment]
Great, I'll track the issue there. Thanks!
