### ISSUE TITLE
Do children of auto-fit column tracks automatically span all tracks if the number of items is less than the number of tracks?

### ISSUE THREAD

**Issue by morganfeeney** [rachelandrew/cssgrid-ama#157]
Hi Rachel,

Here's the [reduced test case](https://codepen.io/morganfeeney/pen/gyNOpL?editors=1100)

Screen shot:
![image](https://user-images.githubusercontent.com/1900222/57011508-e8e71d80-6bf9-11e9-999a-90afc96ff54b.png)

In the screenshot you'll notice that there are 5 column tracks, is the button spanning all 5 tracks? Visually, it appears to be the case, however, when I inspect the button there is no computed CSS rule that shows that information, e.g. I would possibly expect to see `grid-column: span N`.

**Comment by rachelandrew** [comment]
No they don't, but if you use auto-fit the empty tracks collapse to 0. Use auto-fill if you don't want that to happen.

**Comment by morganfeeney** [comment]
Thanks for the clarification! I was aiming for what I get with `auto-fit`.

Could the empty tracks be an issue for any reason that you can think of?
I'm thinking that if I specified a number of columns for the items to span then that would be an issue, but in this case I want the items to fill the available space without doing that.

**Comment by rachelandrew** [comment]
Well it's fine if you will only ever have that one row, but as soon as you add items in a row below then the tracks won't be empty and it will revert to the same behaviour as auto-fill.

**Comment by morganfeeney** [comment]
Thanks!
