### ISSUE TITLE
Is equal height for all row possible with cssgrid?

### ISSUE THREAD

**Issue by Shaderpixel** [rachelandrew/cssgrid-ama#16]
Hi Rachel, first off thanks for doing this AMA. Something that has been on my mind for quite awhile when working with Flex is that when rows wrap, the height of the row is dictated by the child that has the tallest content. Not that it is bad, and I understand this is the one dimensional calculation that is part of the Flex spec. 

When we talk about two dimensional in cssgrid, does that mean there is a way to overcome this and specify that all wrapped rows can have equal height despite some rows will have shorter content? I forked your pen just to show you what I am talking about. [http://codepen.io/Shaderpixel/pen/oBLoZM](http://codepen.io/Shaderpixel/pen/oBLoZM) The changes are in the grid area.

Thank you.

**Comment by rachelandrew** [comment]
I'm not sure what you are trying to show with that pen but you can set the height of grid rows that are generated in the implicit grid with the `grid-auto-rows` property.

If you are creating an explicit grid then you can create the track sizing in your definition.

More usually what you will actually want is to set a minimum size, to prevent overflows if there is more content than expected. in that case you can use minmax(), making a minimum size for the track but a maximum of auto.

**Comment by Shaderpixel** [comment]
I have edited the pen. When card 4 and 5 wraps to a new row, the height of those cards take on the card height of the card with the most content. In this case card 5, which is different from the card height of card 1-3. I was wondering if there is a way for cards in both rows to have the same height.

From your explanation, it seems like I will have to use minmax() to set the track sizes, but correct me if I am wrong, that will still mean that I will have one row taller than the other because of maximum of auto?

**Comment by rachelandrew** [comment]
Yes, but you don't tend to want overflows. If you do want an overflow then just set an explicit height and the content will overflow.

See: http://codepen.io/rachelandrew/pen/QdEBpj

(the overflow behavior is behaving differently in browsers atm, but you get the idea)

**Comment by Shaderpixel** [comment]
Got it. Much appreciated Rachel, you can close this now.
