### ISSUE TITLE
Grid item which has a `fixed` `position`

### ISSUE THREAD

**Issue by ror-y** [rachelandrew/cssgrid-ama#17]
I have a grid layout which has a grid-item sidebar which sits to the right hand side of another 'main-content' grid-item.

However, on small screens, I want this sidebar to have `position: fixed` and sit on top of the 'main-content' div.

Here is my solution: https://jsbin.com/cusahu/edit?html,css,output

Is using `position: fixed` a good approach to this issue, or on mobile/tablet should the sidebar not be part of the grid?

**Comment by rachelandrew** [comment]
I'm not sure what the problem you are having is? Did you want it to overlay? If not you could place it into the second row of a redefined grid for narrow widths.

**Comment by ror-y** [comment]
My issue really is the question of what constitutes a grid item. On a large screen, the sidebar is very much a grid item, but on smaller screens, the very same section is less part of the actual grid layout and more an overlay on top of another grid item.

**Comment by rachelandrew** [comment]
A grid item is any direct child of the element you have set to display: grid. So if something is structurally a direct child, it is going to be a grid item and can participate in the layout. So the decision is probably more to do with markup than grid layout.
