### ISSUE TITLE
Grid items who take up the available horizontal space

### ISSUE THREAD

**Issue by ror-y** [rachelandrew/cssgrid-ama#18]
I have a grid containing 16 grid items.

I want the top row to take 4 grid items, second row 3, third row 2 and fourth row 7. I want each of them to be evenly spaced so that they take up all the available space.

I can to an extent achieve this by specifying a number in `grid-template-columns`, i.e. 12, and using  `grid-column-end: span-*` on grid items. However this is not adequate for the row in which I want 7 items spaced evenly.

Code example of expected behaviour using `grid-column-end` on grid items (apart from the final row with 7 items, whose last item forces itself into a row not specified in grid-template-columns): https://plnkr.co/edit/20iQPmscvdEIKepzAIfL?p=preview

My idea to solve this is to use `auto-fill` in the `grid-template-columns` property, but does not address the separate rows.

Code example of using`auto-fill`: https://plnkr.co/edit/dFxbT3SSureeTMVioaGH?p=preview

Is such a behaviour possible with CSS Grid?

**Comment by rachelandrew** [comment]
This seems like you are trying to solve a problem better solved by flexbox using Grid.

Grid is two dimensional, so you create columns and rows when you declare something a grid, then you fit your things into those columns and rows. So assigning of space happens on the grid as a whole not on a row by row basis.

If you want row by row - that's really what flexbox is for.
