### ISSUE TITLE
Is it possible to rotate each cell? (answered)

### ISSUE THREAD

**Issue by tobireif** [rachelandrew/cssgrid-ama#2]
Is it possible to rotate each cell? (eg each one in a different way?)

**Comment by rachelandrew** [comment]
Not sure I follow! Can you draw an example of what you are trying to achieve?

**Comment by tobireif** [comment]
Here's a slightly silly example:

http://codepen.io/anon/pen/GNRBzr

(Works in Chrome with the "experimental Web Platform features" flag enabled.)

I answered my own question, sorry, but thanks for the AMA!

**Comment by tobireif** [comment]
Reopening so that the question ticket gets listed in the nav.

(Feel free to close if that's not how you want it to work.)

**Comment by tobireif** [comment]
For anyone who came here from the link in the tweet:

My code in the forked codepen demo doesn't work, try eg

```
.box1, .box3 {
  transform: rotate(-20deg);
}
.box2, .box5 {
  transform: rotate(20deg);
}
```
