### ISSUE TITLE
Why use named track lines over `grid-template-areas`?

### ISSUE THREAD

**Issue by ror-y** [rachelandrew/cssgrid-ama#20]
Comparing named track lines in `grid-template-columns` to `grid-template-areas`, I find myself constantly reaching for the latter.

For me there are several advantages of using `grid-template-areas` that you don't get with named track lines:

- Instantly recognisable snapshot of what your grid will look like across breakpoints.
- No cluttered, potentially difficult to understand `grid-template-columns` setting.
- No having to look in the grid-item's selector to see how much room it takes up (`grid-column` & `grid-row`).

Are there cases in which I should be using named track lines instead of `grid-template-areas`? Do you have a preference?

**Comment by rachelandrew** [comment]
I'd suggest using what works for you!

Note that if you have a named area, you also have named lines anyway (and vice versa).

http://gridbyexample.com/video/magic-lines-and-areas/

**Comment by ror-y** [comment]
Thanks, I found that useful.
