### ISSUE TITLE
Setting the width of Grid-columns

### ISSUE THREAD

**Issue by Neha** [rachelandrew/cssgrid-ama#21]
Hey Rachael,

As per the documentation, by using grid-column-templates it will set the number of columns and width too. In the codepen link I am setting column width to 100px but it is rendering to 260.41px. Why? How can I fix the width of column to 100px only?

[Codpen] (http://codepen.io/NehhaSharma/pen/xggjNy)

**Comment by Neha** [comment]
Hey,

I got the solution hence I closed it. I declared parent container width to fr due to which the widths were varying. 

You can close it.

Thanks,
Neha

**Comment by rachelandrew** [comment]
The `grid-template-columns` property requires a track listing. So if you want three 200 pixel columns you need to use:

`grid-template-columns: 200px 200px 200px;`

or

`grid-template-columns: repeat(3,200px);`

In your example you are creating a one track grid, and then the additional tracks are being created in the implicit grid, auto-sized by default. So they are taking up the rest of the space in the 800px wide container.

If you only want to give a single value for all generated columns then you could use:

`grid-auto-columns: 200px;`
