### ISSUE TITLE
What benefits does grid-gap have over using margins?

### ISSUE THREAD

**Issue by Ollie-w** [rachelandrew/cssgrid-ama#22]
I am asking particularly thinking about progressive enhancement. Margins will need to be used for browsers that don't support grid anyway. It seems easier just to use margins rather than using grid-gap then having an @supports margin fallback.

**Comment by rachelandrew** [comment]
Like most things it is going to depend on what you are building.

If you use margins you will have to do the work yourself of accounting for the margins on the outside of the grid (as we currently have to do for flexbox). But there is no "one true way". You have a set of tools in CSS that can create layouts, how you use them is pretty much up to you. If the end result works and checks out in terms of a11y and performance then there isn't a right or wrong.
