### ISSUE TITLE
Fixed position grid items

### ISSUE THREAD

**Issue by ror-y** [rachelandrew/cssgrid-ama#24]
I want to use a grid layout which has a main-content section sandwiched by two sidebars. The main content scrolls, while the sidebars have fixed positioning. This is roughly how Facebook behaves.

So my approach to this is to set a simple grid layout with 3 columns like so:

![screen shot 2017-01-22 at 15 21 39](https://cloud.githubusercontent.com/assets/10364894/22183460/e7da52de-e0b6-11e6-8183-b97f6163e479.png)

However, as soon as the `aside`s are given a `fixed` `position`, things go crazy:

![screen shot 2017-01-22 at 15 21 54](https://cloud.githubusercontent.com/assets/10364894/22183466/03bb3ae0-e0b7-11e6-9d54-223211c1c3a5.png)

The width rules that once applied (as specified in `grid-template-columns`) no longer apply, and both `aside`s start from top left.

Is there a nice way to have fixed position sidebars for the main-content to scroll?

demo: http://codepen.io/alanbuchanan/pen/ZLKxYM?editors=1100#0

**Comment by ror-y** [comment]
Ok, after playing around I think the best solution is not to use any fixed positioning, but just stick a `max-height` on the main-content, and use `overflow: scroll` or `overflow: auto` on it.

This renders the desired result as can be seen here: http://codepen.io/alanbuchanan/pen/mRmxWR?editors=1100#0

Still curious though what your preferred solution is?

**Comment by rachelandrew** [comment]
I looked into this and position: fixed resolves to position: absolute, as the containing block is then not a grid container you get the same behaviour as if you had not made the grid a container with position relative.

As noted in the below issue, position: sticky might be a possible solution.

https://github.com/w3c/csswg-drafts/issues/977

**Comment by fantasai** [comment]
Ummm... that's not quite right. `position: fixed` doesn't resolve to `position: absolute`, it's just that fixed positioning is considered a subset of absolute positioning, with the containing block being the rectangle of the viewport instead of being the padding-box of an element on the page. Since the viewport isn't a grid container, you can't use grid properties on it; it's just a rectangle.

**Comment by rachelandrew** [comment]
thanks @fantasai and yes 'resolves' is not a great word to use.

**Comment by Shaderpixel** [comment]
If it helps, you might have already figured this out, you can wrap your contents in <aside> in a div and set the div to have position: fixed, that will produce the result you expected.

[http://codepen.io/Shaderpixel/pen/BRZNrE?editors=1100](http://codepen.io/Shaderpixel/pen/BRZNrE?editors=1100)
