### ISSUE TITLE
`1fr` and `minmax(0, 1fr)` yield different behavior

### ISSUE THREAD

**Issue by surma** [rachelandrew/cssgrid-ama#25]
[Live demo](https://jsbin.com/yenupe/2/edit?html,css,output)

If you define

```CSS
  grid-template-columns: repeat(2, 1fr);
```

I’d expect my columns to get as small as necessary to fit into the container. That is however not the case if the grid items’ combined intrinsic width is bigger than the grid container’s width.

Apparently, you have to set

```CSS
  grid-template-columns: repeat(2, minmax(0, 1fr));
```

to achieve the desired effect.

Here’s a GIF. Top row has `1fr`, bottom row has `minmax(0, 1fr)`.

![im-0 0 -0](https://cloud.githubusercontent.com/assets/234957/22296359/d0181584-e311-11e6-8e41-42cdc2b1fdfc.gif)

What is the explanation? I seems rather unintuitive to me.

**Comment by surma** [comment]
As an interesting side-note: Setting `overflow: hidden` or `min-width: 0` on the grid items also work as _a_ solution (with different side-effects).

**Comment by rachelandrew** [comment]
In the first instance you are leaving it to the browser to decide what the minimum size should be, in the second you have made that decision to set it to zero.

https://drafts.csswg.org/css-grid/#min-size-auto

also, read the stuff in the Flexbox spec about automatic minimum size https://drafts.csswg.org/css-flexbox-1/#automatic-minimum-size
