### ISSUE TITLE
Changing DOM inside css-grid colums

### ISSUE THREAD

**Issue by prateekjadhwani** [rachelandrew/cssgrid-ama#27]
I am currently working on a CMS that uses css-grid. I observed that if I have one div with 

```css
grid-column-start: 1;
grid-column-end: 5;
```

And another div 

```css
grid-column-start: 5;
grid-column-end: 10;
```

It shows perfectly time. I go to dev tools or use js to change the HTML for the second div, the width of divs change. I am not sure why it's happening. Is it a bug?

I tried this on recent version of chrome.

**Comment by rachelandrew** [comment]
I would need to see a complete example, as it is likely that the grid definition is where your confusion lies.

Make a CodePen or similar http://codepen.io/ that demonstrates the issue as a reduced test case.

**Comment by prateekjadhwani** [comment]
Hi @rachelandrew 
I just created a codepen demo
http://codepen.io/prateekjadhwani/pen/mRqrwr

That is what I was talking about

**Comment by rachelandrew** [comment]
You haven't defined any column tracks, so the grid is creating implicit tracks which will be auto sized. That means they will change according to the content.

You need to create column tracks and give them sizing information using the `grid-template-columns` property.

Have a look at the first few videos here http://gridbyexample.com/video/

**Comment by prateekjadhwani** [comment]
Thanks @rachelandrew  that was really hepful.

Is there a way that I can set it for dynamic width. 

```css
grid-template-columns: repeat(12, calc(100% / 12));
```
Some thing that would make it use `n` children for  variable parent width?

Thanks

**Comment by rachelandrew** [comment]
Yes: http://gridbyexample.com/video/series-auto-fill-auto-fit/

**Comment by prateekjadhwani** [comment]
Thanks @rachelandrew  that did increase my knowledge about css grids.

Closing the issue now. Once again, thank you :)
