### ISSUE TITLE
Does CSS grid ever animate?

### ISSUE THREAD

**Issue by simonhbor** [rachelandrew/cssgrid-ama#28]
Am I right that grid does not allow any animations? Or could just be my browser? Imagine having a classic sidebar with nav layout. Clicking a button would hide the sidebar. Without grid you could you transform or max-widthto move the sidebar. Using grid, the same simple effect does not seem possible

**Comment by rachelandrew** [comment]
Without a code example it is hard to know what you are trying to achieve. "Imagine some code ... why isn't it working?" isn't something I can answer.

The specification details what can and can't be animated. [For example the tracks can as detailed here](https://www.w3.org/TR/css-grid-1/#track-sizing). Also remember there is no requirement to have your entire layout as a grid, in the case of a sidebar I probably wouldn't have that in the same grid as some content if I was wanting to hide it.

**Comment by simonhbor** [comment]
Thanks for the link about tracks! OK here is code that definitely does not work with respect to showing any animation (in latest Chrome - not canary). Grid seems so good for this kind of layout, so it's a shame not to use it for something like this
`.grid-with-sidebar {
    display: grid;
    grid-template-columns: 250px 1fr;
    transition: all 1s;
}
.grid-with-sidebar.narrow-sidebar {
    grid-template-columns: 10px 1fr;
}
`

**Comment by rachelandrew** [comment]
Pop a code example onto CodePen or similar.

**Comment by tomByrer** [comment]
https://codepen.io/matuzo/post/animating-css-grid-layout-properties

Gaps animate in Firefox & Edge, still not in Chrome Canary.

**Comment by coolemur** [comment]
Animating row/column width and height would be nice. 

https://codepen.io/coolemur/pen/MGMvEz
