### ISSUE TITLE
Why would you want multiple grid lines with the same name?

### ISSUE THREAD

**Issue by ror-y** [rachelandrew/cssgrid-ama#30]
In the [documentation](https://www.w3.org/TR/css-grid-1/) I see ways to give more than one grid line the same name as another. For example, [Example 17](https://www.w3.org/TR/css-grid-1/#repeat-notation):

```
This example shows two equivalent ways of writing the same grid definition. Both declarations produce four “main” columns, each 250px wide, surrounded by 10px “gutter” columns.
grid-template-columns: 10px [col-start] 250px [col-end]
                       10px [col-start] 250px [col-end]
                       10px [col-start] 250px [col-end]
                       10px [col-start] 250px [col-end] 10px;
/* same as above, except easier to write */
grid-template-columns: repeat(4, 10px [col-start] 250px [col-end]) 10px;
```

Why would you want to give multiple lines the same name? How do you refer to them individually by name if their name isn't unique?

**Comment by rachelandrew** [comment]
You can then do something like:

~~~
.item {
  grid-column: col-start 2 / col-end 4;
}
~~~

or 

~~~
.item {
  grid-column: col-start 2 / span 2;
}
~~~

So `col-start 2` is the second line named col-start.

Example here: http://gridbyexample.com/examples/example8/
And here: http://gridbyexample.com/examples/page-layout/#layout12
