### ISSUE TITLE
Use grid to design upon a visual grid.

### ISSUE THREAD

**Issue by morganfeeney** [rachelandrew/cssgrid-ama#32]
Hi Rachel, really looking forward to trying grid. I've held back, namely because I decided to study a book: Grid Systems in Graphic Design by Josef Mülller-Brockmann — before immersing myself — and have been applying the principles to [Interior](https://github.com/morganfeeney/interior/) in a feature branch. I thought I'd be better equipped to use the grid by doing this in advance.

What I have learnt, is that I haven't been using a visual grid for layout in the browser — in fact I picked up some bad habits though using 'grid systems' created by nice web folk, which I never really questioned — I strongly believe this has led me to misunderstand the purpose of a web grid system, as a result I have created many layouts 'by eye'.

Do you think it would be beneficial to have a way to display a master grid of some sort that can be used to layout a design using CSS grid, is this something that should/could be part of the spec? We have this fantastic tool for _development_, but speaking from the point of using it to _design_ have we moved any further along from where we have been with float based grid systems?

**Comment by rachelandrew** [comment]
This seems like something browsers would address, or some kind of authoring tool. I'm not sure how it relates to the specification itself.

**Comment by morganfeeney** [comment]
Firefox have created a tool that displays a grid, so I suppose that could be used if using Firefox. But I want to use all browsers and I want the grid used for design layout to be consistent.

In terms of the spec, why is there no visual aspect to it?

**Comment by rachelandrew** [comment]
I don't understand what you mean by "why is there no visual aspect to it"

**Comment by morganfeeney** [comment]
If the point of it is to use it to layout a design in the browser why not have some visual indication so a user may see where the grid cells/columns/rows/gutters etc. are when using it?

**Comment by rachelandrew** [comment]
When "designing with it" that still sounds very much like the remit of authoring tools or browser DevTools.

There are issues already raised for the ability to add borders and background colours to grid lines/cells and so on, however tools "for designing" are not usually the remit of a CSS specification. I don't know of any other spec where that is the case.

**Comment by morganfeeney** [comment]
Without some visual reference baked in I'm going to have to create some sort of system that works with grid based upon configuration — which is something I could do (it will mean more development time), maybe not the case for other design folk who possibly want to get their hands dirty and try using it.

I suppose the way I'm thinking about how I can use this is from the perspective of design, not development, even though I'll have to code to use it.

Out of interest, when authoring the spec was there any reference to books like I mentioned in my original comment?

**Comment by rachelandrew** [comment]
Visual tools have typically been things developed by people other than the CSS Working Group. So I would expect that people will develop such tools for grid layout as they have for every other layout method. I still don't understand what you expect this spec to do differently to every other part of CSS so perhaps you are arguing with the wrong person!

**Comment by morganfeeney** [comment]
It's a ground-breaking moment in CSS history — I'm genuinely curious about it — thanks for taking the time to explain things.

**Comment by morganfeeney** [comment]
For reference—in case anyone reads this and wonders what the hell I was on about—this is the result of what I was alluding to: https://interiorsystem.co.uk/
