### ISSUE TITLE
How to build RTL support on CSS Grid

### ISSUE THREAD

**Issue by pedrAngular** [rachelandrew/cssgrid-ama#36]
I was wondering if CSS Grid support RTL in some way, or how could be the best way to support it in our CSS Grid Layout projects.

Example layout looking for RTL support: http://codepen.io/fsabate/pen/evYBeJ

**Comment by rachelandrew** [comment]
Grid is designed to work with Writing Modes. If you are in a rtl language then line 1 of your grid will be on the right hand side of the grid rather than the left. It's baked into the specification to work, hence all of the `start` and `end` rather than `left` and `right`.
