### ISSUE TITLE
Grids and Images

### ISSUE THREAD

**Issue by ashleypetersondesign** [rachelandrew/cssgrid-ama#38]
What are some of the best or recommended methods for adding images to grids

**Comment by rachelandrew** [comment]
I'm not sure I understand the question. There isn't any difference adding an image to a grid layout to adding an image to a flex layout or anything else.

If you are having a problem with some code then put together a CodePen example and I will take a look.

**Comment by ashleypetersondesign** [comment]
Hi Rachel,

Thanks so much for your quick response. 

I was apprehensive about posting my questions, as I'm a web design student. I apologise if it seemed rudimentary. We learned a bit about grid layouts and with a background in print design, this made me really excited. 

My new born web designer brain is struggling to translate the tutorials on sites such as Grid By Example, with actual content such as images.

I was working on a code pen to show you what I was having a problem with and realised that my grid column/row units were off, and thats what was causing a load of issues... one little number changed did the fix haha

Thanks again for getting back to me, and this is such exciting stuff!
