### ISSUE TITLE
auto-fill an even number of columns

### ISSUE THREAD

**Issue by Rothrock42** [rachelandrew/cssgrid-ama#4]
I wanted to use auto-fill to make as many columns as would fit in my area, but I wanted to ensure that I had an even number of columns. I tried

```
.wrapper{
   display:grid;
   grid-template-columns: repeat(autofill, 5vw 5vw);
}
```

This works in Chrome, but gives an `invalid property value` in all my FireFoxes (I've turned on the flags in regular and developer) and have 52.0a1 for nightly.

If I replace the auto-fill with a specific number it works.

Is there some other way to have as many repeating patterns as will fit?

**Comment by rachelandrew** [comment]
A track list is valid https://drafts.csswg.org/css-grid/#repeat-syntax and is implemented in Blink.

So this works in Chrome http://codepen.io/rachelandrew/pen/aBOyEo

**Comment by Rothrock42** [comment]
Cool. Thank you. I'm just getting into this and it is hard to tell if it is me or just not implemented in browser X yet.
