### ISSUE TITLE
justify-content & align-content: stretch

### ISSUE THREAD

**Issue by enxaneta** [rachelandrew/cssgrid-ama#40]
For now I'm just testing the grid layout. Just trying to learn. 
I have this problem with justify-content & align-content. Although it works as expected for start, end, center, space-around, space-between & space-evenly, when I'm using justify-content || align-content: **stretch** the result is the same as for **start** (maybe because **start** is the default). What am I doing wrong?
This is the codepen example:
http://codepen.io/enxaneta/pen/xqwrgE?editors=0100

**Comment by rachelandrew** [comment]
You have given everything a size in absolute units, so they won't stretch. I'm not sure what else you would expect to happen in that case.
