### ISSUE TITLE
With Grid Layout, we can substitute Pinterest Grid Layout that is created with JS?

### ISSUE THREAD

**Issue by Lucasktrindade** [rachelandrew/cssgrid-ama#41]

**Comment by webcraftsman** [comment]
Lucas, you should look at this closed issue, https://github.com/rachelandrew/cssgrid-ama/issues/19. CSS Grid cannot replace Masonry JS solutions for a Pinterest type layout. Rachel addresses this in the issue I cited.

**Comment by Lucasktrindade** [comment]
Thanks @webcraftsman, i'll read this issue.
