### ISSUE TITLE
Images as Grid items

### ISSUE THREAD

**Issue by rctneil** [rachelandrew/cssgrid-ama#46]
How should images react if they are a grid item?

I have an example here which reacts differently in Firefox to Chrome: http://codepen.io/rctneil/full/qrmqer

In FF, the image is contained within the item but in Chrome it expands to full width and height. It is the small logo in the top right I am discussing.

Thanks,
Neil

**Comment by rachelandrew** [comment]
I can't see any difference. What I would suggest is to create a reduced test case that just shows your issue. No Sass, no other elements. Then post that here if creating that test case doesn't help you figure it out for yourself.

**Comment by rachelandrew** [comment]
Closing as no test case provided, feel free to reopen.
