### ISSUE TITLE
Fluid layout

### ISSUE THREAD

**Issue by ledahulevogyre** [rachelandrew/cssgrid-ama#47]
I want a 1 column, 4 rows grid with all rows being the intrinsic height, except the 3rd one that must resize with the viewport.

With flex, I did that
```
<section>
 <article>AAA</article>
 <article>BBB</article>
 <article class="expand">CCC</article>
 <article>DDD</article>
</section>
```

```
section {
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}

.expand{
	flex: 1;
}

```
Is the following the right way to achieve the same effect with grid ?
```
section  {
	min-height: 100vh;
	display: grid;
	grid-template-rows: 0fr 0fr auto 0fr;
}
```

It works. But are the 0fr's ok ?

**Comment by webcraftsman** [comment]
@ledahulevogyre If you are only doing one column, then Flexbox would be the right tool, not CSS Grid. As Rachel has written several places, Flexbox is right tool for one-dimensional layout (row or column) and CSS Grid is a right tool for two dimension layouts (rows and columns).

**Comment by ledahulevogyre** [comment]
Thank you @webcraftsman .
Well I was just simplifying my use case. 
I might add more columns to my layout, and my question remains.

**Comment by rachelandrew** [comment]
and the simplification is very much appreciated :)

I would do:

```
section  {
	min-height: 100vh;
	display: grid;
	grid-template-rows: auto auto 1fr auto;
}
```

`auto` will take the content size. The `1fr` will take up any available space left in the container.

**Comment by ledahulevogyre** [comment]
Thank you for your response Rachel.
Unfortunately, I can't make your suggestion working 
https://codepen.io/anon/pen/vxWMGJ
I want the opposite : the third article (CCC in blue) to expand. And the three other ones to fit to their content.
Am I missing something ?
I'm using Firefox 52.

**Comment by rachelandrew** [comment]
It works in Chrome, that looks like a FF bug. If you look at the spec example here https://www.w3.org/TR/css3-grid-layout/#adapting-to-available-space it essentially is what you are asking for and uses a pattern of tracks like my example. So I think in terms of the spec this should work.

**Comment by rachelandrew** [comment]
If you do `height` rather than `min-height` on the container it works. Obviously you want `min-height` but there is something off here :)

**Comment by ledahulevogyre** [comment]
Thank you.
Hmmm too bad for that bug.
Have you reported it, or do you know if someone has ?

What do you think about 0fr 0fr auto 0fr ? Does it make any sense ?

**Comment by ledahulevogyre** [comment]
For anyone's information, it has been fixed in Firefox 53.
