### ISSUE TITLE
Will cssgrid completely replace serious grid frameworks?

### ISSUE THREAD

**Issue by Timoti** [rachelandrew/cssgrid-ama#49]
I've loved using susy for some years now, it beats the pants off BS and  Foundation's offerings. 

Right now I'm wondering cssgrid can complately replace the better grid frameworks like Susy and Jeet. I'm thinking maybe… context, containment, some functions might still be useful, but can't see all that floaty stuff coexisting with cssgrid, even if theoretically susy will support different display properties  (and that I've managed to get susy and flexbox to play reasonably nicely in the past).

So I've wondered, what are your thoughts on the future of css frameworks now - both longer term and in transition as a few older browsers may need to be supported?

**Comment by rachelandrew** [comment]
I think Grid replaces a lot of the reasons we have these frameworks (eg. calculating complex percentages to do a float based layout). There may well be ways in which tools can add value in terms of workflow, but I'd suggest people learn how to use Grid first. Then see where the edges are.
