### ISSUE TITLE
View the gridlines

### ISSUE THREAD

**Issue by acnorrisuk** [rachelandrew/cssgrid-ama#5]
When creating complex grids (especially when using a lot of line placement), it would be useful to see the grid lines on the page. 

We often do this for other elements in CSS by using something like `outline: 1px solid red;`

Have you come across any way of overlaying grid lines in this way as a development tool?

**Comment by rachelandrew** [comment]
As you can't put borders on the grid areas this isn't easy to do directly in CSS. However there are already browser Dev Tools on the way. There is an add-on for Firefox that gives some simple functionality https://addons.mozilla.org/en-US/firefox/addon/css-grid-inspector/

Firefox are also working on a grid tool as part of their dev tools, I saw an early stage demo from one of the developers so I think we'll be getting tooling to help us with this.
