### ISSUE TITLE
What is the smallest default grid cell?

### ISSUE THREAD

**Issue by sunright** [rachelandrew/cssgrid-ama#51]
Rachel,

Thank you sharing and promoting your love and passion. 

**CSS Grid Layout Specification Question:** 
if  A **grid cell** is the intersection of a grid row and a grid column. 
and 
if a grid cell is the **smallest unit of the grid** that can be referenced when positioning grid items.

Is there a smallest default physical grid cell size defined by the Specification?
or Maybe the question should be about tracks size because  i believe row/column track size define cell.
Is there a smallest default physical track size defined by the Specification?

really just interested in the theoretical limits of small physical unit of grid.

Thank you,
Robert

**Comment by rachelandrew** [comment]
There isn't a minimum, tracks can collapse to nothing if they are empty.

**Comment by sunright** [comment]
Rachel,

I forgot to Thank you for your time and answer.

Thank you!! :-)

Robert DiBlasi
We all learn by sharing what we know
