### ISSUE TITLE
Can we put class name/elements name in 'grid-areas'?

### ISSUE THREAD

**Issue by Neha** [rachelandrew/cssgrid-ama#52]
Hey,

Suggestion - can we assign class Name and elements name when defining grid-areas?

It will be easy as a dev to manage the layout from the CSS Grids. As of now, I have to remember the area names and classnames too.

Thanks
Neha

**Comment by rachelandrew** [comment]
I'm not sure I understand, you define your area on a selector (which might be a class). I'm not really sure what behaviour you are asking for.
