### ISSUE TITLE
Why the columns are taking extra width?

### ISSUE THREAD

**Issue by Neha** [rachelandrew/cssgrid-ama#54]
Hello,

I was trying to implement the subgrid (which is not supported on browser yet) hence by grid only I am trying to create Nested Grids. The issues are -

1) columns - aboutus, services, contact is taking extra width. Why is so?
2) Midsection is declared grid , but I haven't defined any columns. Then why H2 is behaving as columns? To take the 100% space in layout I have to use span

[http://codepen.io/NehhaSharma/pen/jBvdXz](http://codepen.io/NehhaSharma/pen/jBvdXz)

Thanks,
Neha

**Comment by rachelandrew** [comment]
1. Where is it taking extra width? I don't understand what you are expecting to see.
2. You have set a grid-column-end so you are getting columns created in the implicit grid

**Comment by rachelandrew** [comment]
You might find it helpful to use Firefox and the grid inspector tool in DevTools.
