### ISSUE TITLE
How do older browsers lacking support for Grid cope

### ISSUE THREAD

**Issue by RobertDeniszczyc** [rachelandrew/cssgrid-ama#56]
Looking at current usage relative stats on caniuse for CSS Grid there appears to be a vast majority of users who are using browsers lacking support for Grid. I've seen a lot of recent tutorials/intros to Grid saying you should be using Grid for your fundamental page layout - how do these older browsers cope with Grid? Is there a fallback or would the layout be completely broken?

Link: http://caniuse.com/#search=CSS%20Grid

Thanks,
Rob

**Comment by rachelandrew** [comment]
Interactions between layout methods are defined in the specification.

See: https://rachelandrew.co.uk/archives/2017/03/20/css-grid-fallbacks-and-overrides/
