### ISSUE TITLE
Ultimate solution is...

### ISSUE THREAD

**Issue by amdad** [rachelandrew/cssgrid-ama#57]
I saw... there are Masonry questions here.  But, why to ask for Masonry if ultimate freedom of layout solution is [Packery](http://packery.metafizzy.co/). 

So? What do you think @rachelandrew Will CSS ever allow us to replace Packery by pure  CSS solution. CSS Grid is close to it I think. But CSS Grid is strictly tabular, not so flexible and universal. I just asking. Will W3C ever comes with this kind of full "**CSS Auto**(placing layout)"? Or JS solution stay only solution for this kind of _intelayout_?

Thank you Rachel for your work on modernizing web!

**Comment by rachelandrew** [comment]
Packery seems to be about the draggable ability as far as I can see, but I don't know it, so I can't really say one way or the other.

**Comment by amdad** [comment]
In my question I didn't mean dragging feature. I asked about packing irregular boxes as tight as it can be without gaps. Logic on CSS Grid is strict. Here is total freedom. 

Like CSS Grid with col/row size to be 1px auto repeat. ;)

**Comment by rachelandrew** [comment]
If you have actual use cases then this is already detailed in [this thread](https://github.com/rachelandrew/cssgrid-ama/issues/19) and in the link issue on the CSS WG github.
