### ISSUE TITLE
grid gaps  /gutter 

### ISSUE THREAD

**Issue by pirloxian** [rachelandrew/cssgrid-ama#58]
Hello, is there a way to hide the gutter in the rows column or have one colour for the content area and another colour for the body background

**Comment by rachelandrew** [comment]
That seems to be two different questions.

I'm not sure wha you mean by hide the gutter. You don't need to have a gutter, set `grid-column-gap` if you only want a column gap and not a row one.

The second, do you mean change the colour of a grid cell? Again, I'm unclear as to the question but at the moment you need to have an element to add borders or colour etc. As detailed in this issue on the spec: https://github.com/w3c/csswg-drafts/issues/499

**Comment by pirloxian** [comment]
kindly run the code below ,and see what i meant  ,
the lines between the header and main content isit possible not to be visible?



<!DOCTYPE html>
<html>
<head>
<link rel="stylesheet" type="text/css" href="tam.css">
</head>
<body>



<div class="grid-container">
  <div class="grid-element header">
  
  
 <ul id="menu">
		<li><a href="#">HOME</a></li>
		<li>
			<a href="#">SAVINGS </a>
			<ul class="hidden">
				<li><a href="#">FIXED DEPOSIT ACCOUNT</a></li>
				<li><a href="#">BIASHARA ACCOUNT</a></li>
				<li><a href="#">PLOT DEV ACCOUNT</a></li>
			</ul>
		</li>
		
		
		
		<li>
			<a href="#">LOANS </a>
			<ul class="hidden">
				<li><a href="#">SHORT TERM LOANS</a></li>
				<li><a href="#">LONG TERM LOANS</a></li>
			
			</ul>
		</li>
		
		
		<li>
		<a href="#">MEMBERSHIP</a>
		<ul class="hidden">
				<li><a href="#">OPENING AN ACCOUNT</a></li>
				<li><a href="#">STATUTORY INFORMATION</a></li>
				<li><a href="#">INVESTMENT SHARES</a></li>
				<li><a href="#">SACCO DEPOSITS</a></li>
				<li><a href="#">MEMBER INFORMATION FORUM</a></li>
				<li><a href="#">FLEXIBLE BANKING</a></li>
			
			</ul>
			</li>
		
		
		
		
		<li><a href="#">ABOUT US</a>
		<ul class="hidden">
				<li><a href="#">WHO WE ARE</a></li>
				<li><a href="#">OUR HISTORY</a></li>
				<li><a href="#">WHAT DRIVES US</a></li>
				<li><a href="#">WHAT MAKES US DIFFERENT</a></li>
				<li><a href="#">CSR</a></li>
				<li><a href="#">CAREERS</a></li>
			
			</ul>	
		</li>
		
		
		
		
		<li><a href="#">INFORMATION CENTER</a>
		
		
		<ul class="hidden">
				<li><a href="#">DOWNLOADS</a></li>
				<li><a href="#">PHOTO GALLERY</a></li>
				<li><a href="#">NEWS &amp; PRESS RELEASE</a></li>
				
			</ul>	
		
		
		</li>
		
		
		
		<li><a href="#">CONTACT US</a>
		<ul class="hidden">
				<li><a href="#">CONTACT INFORMATION</a></li>
				<li><a href="#">FEEDBACK FORM</a></li>
				<li><a href="#">BRANCH NETWORK</a></li>
				
			</ul>	
		
		</li>
		<li><a href="#">FAQs</a>
		
		
		
</li>
	</ul>
  
  
  
  </div>
  
  
  
  
  
  
  
  <div class="grid-element sidebar">Sidebar</div>
  
  
  
  
  
  
  
  <div class="grid-element main">Main Content
  
  
  
  <div class="con">
<img src="1.jpg" class="img">
<img src="2.jpg" class="img">
<img src="3.jpg" class="img">
<img src="4.jpg" class="img">
	
	</div>
  
  
  
  
  
  
  
  
  
  
  
  
  </div>
  
  
  
  
  
  
  
  
  
  <div class="grid-element extra">Extra Content</div>
  <div class="grid-element footer">Footer</div>
</div>



</body>
</html> 

css:




body {
  text-align: center;
  font-family: "Dosis";
  max-width: 990px;
    margin: auto;
    background: #1b471d;
    padding: 10px;
}


/*Strip the ul of padding and list styling*/
ul {
	list-style-type:none;
	margin:0;
	padding:0;
	position: absolute;
}

/*Create a horizontal list with spacing*/
li {
	display:inline-block;
	float: center;

}

/*Style for menu links*/
li a {
	display:block;
	min-width:100px;
	height: 50px;
	text-align: center;
	line-height: 50px;
	font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	color: #fff;
	background: #3c0742;
	text-decoration: none;
}

/*Hover state for top level links*/
li:hover a {
	background: #19c589;
}

/*Style for dropdown links*/
li:hover ul a {
	background: #1b471d;
	color: white;
	height: 50px;
	line-height: 40px;
	text-align: left ;
	
}

/*Hover state for dropdown links*/
li:hover ul a:hover {
	background: black;
	color: #fff;
}
/*Hide dropdown links until they are needed*/
li ul {
	display: none;
}

/*Make dropdown links vertical*/
li ul li {
	display: block;
	float: none;
	
}

/*Prevent text wrapping*/
li ul li a {
	width: auto;
	min-width: 100px;
	padding: 0 20px;
	
}

/*Display the dropdown on hover*/
ul li a:hover + .hidden, .hidden:hover {
	display: block;
}
body {
  text-align: center;
  font-family: "Dosis";
  max-width: 980px;
    margin: auto;
    background: #197524;
    padding: 10px;
}
.con{
	width:512px;
	height: 256px;
	border: 5px solid red;
	margin: 50px auto;
	overflow:hidden;
	position:relative;
	}
	
	.img{
	position:absolute;
	width:512px;
	height:256px;
	animation:mm 15s infinite;
	opacity:0;
	
	}
	@keyframes mm{
	10%{opacity:1}
	45%{opacity:0}
	
	}
	
	img:nth-child(0){animation-delay: 0s}
	img:nth-child(1){animation-delay: 5s}
	img:nth-child(2){animation-delay: 10s}
	img:nth-child(3){animation-delay: 15s}

.grid-container {
  display: grid;
  grid-template-columns: 0.25fr 10px 0.75fr;
  grid-template-rows: auto 20px auto 20px auto 20px auto;
  grid-gap: 0px;
}

.grid-element {
  background-color: w;
  color: #fff;
  padding: 40px;
  font-size: 0.9em;
  
}
.header {
  grid-column-start: 1;
  grid-column-end: 4;
  grid-row-start: 1;
  grid-row-end: 2;
  background: #3c0742;
  height:30px;
 
}



.sidebar {
  grid-column-start: 1;
  grid-column-end: 2;
  grid-row-start: 3;
  grid-row-end: 6;
  background: #3c0742;
}

.main {
  grid-column-start: 3;
  grid-column-end: 4;
  grid-row-start: 3;
  grid-row-end: 4;
  background: #3c0742;
  height:400px;
}

.extra {
  grid-column-start: 3;
  grid-column-end: 4;
  grid-row-start: 5;
  grid-row-end: 6;
  background:#3c0742;
}

.footer {
  grid-column-start: 1;
  grid-column-end: 4;
  grid-row-start: 7;
  grid-row-end: 8;
  background: #3c0742;
}

**Comment by rachelandrew** [comment]
Please create a CodePen or jsBin example of your code - thanks!

**Comment by rachelandrew** [comment]
Closing as no reduced example provided.
