### ISSUE TITLE
Is there a way to build a hexagon grid using CSS grid?

### ISSUE THREAD

**Issue by tnormington** [rachelandrew/cssgrid-ama#59]

**Comment by ghost** [comment]
Jen Simmons tried to create hexagonal layout/gallery [labs.jensimmons.com/2016/](url) - scroll down to see examples.

**Comment by rachelandrew** [comment]
I'd need to see an example of what you are actually trying to do really.

**Comment by rachelandrew** [comment]
Closing as no test case or example image provided.
