### ISSUE TITLE
Can an element be a part of a fixed-width grid while still spanning the full viewport?

### ISSUE THREAD

**Issue by thinsoldier** [rachelandrew/cssgrid-ama#62]
I have a grid of 5 rows and 3 columns. The grid div itself has a max width of 800px and a min-height of 100vh and is centered within the viewport. 

The designer wants the 3rd row to have a background color behind only that row and it must extend from the far left to the far right of the viewport. How can this be done?

At the moment I'm using JS and absolute positioning to find the coordinates of an element in the 3rd row and positioning an empty div to be the background color. Feels like faux-columns all over again.

**Comment by webcraftsman** [comment]
@thinsoldier I tried to take a crack at your layout problem. I see this type of situation in a lot of designs I code so I wanted to experiment and try to find a solution.

[I used a combination of Grid and Flexbox and generated content to solve the problem](http://codepen.io/webcraftsman/pen/OmLOEv). I tried to do it without generated content and could not come up with a solution. If there was an offset property in Grid, I might have been able to get it to work. Not sure if it will help you or not but thought I would offer it.

**Comment by webcraftsman** [comment]
@thinsoldier [Another experiment](http://codepen.io/webcraftsman/pen/RVbBrG) with a background image and an inner grid.

**Comment by SherriAlexander** [comment]
I noticed that on a very wide monitor, the pseudo-elements in the experiments above don't extend all the way to the edge.  I forked your Grid/Flexbox experiment on CodePen and [tinkered with it a little](http://codepen.io/SherriAlexander/pen/pPvyyy), using a variation on a calc/vw unit trick I've been using lately.

Just starting to wrap my head around CSS Grid, so this was a fun exercise!  I'll have to play with it some more (didn't browser test or work in mobile-first responsiveness yet).

**Comment by webcraftsman** [comment]
Thanks @SherriAlexander.

**Comment by thinsoldier** [comment]
Regarding http://s.codepen.io/SherriAlexander/fullpage/pPvyyy? the great thing about grid is it allows me to not need to have multiple "row" wrapping divs that only contain 3 elements each. Does your demo still work if you remove them?

**Comment by rachelandrew** [comment]
http://codepen.io/rachelandrew/pen/JNorLZ

You are going to need generated content if you want to put a background on an empty grid area. You can get something as you wanted with a single grid by setting outer tracks as 1fr each which will center the middle tracks. 

Note the minmax in the track listing to get your inner tracks, you could use various sizing methods but would need to deal with making sure it added up to no more that 800 pixels in some way.

**Comment by SherriAlexander** [comment]
I hadn't thought of making the pseudo-element a positioned grid child too -- that's a great solution!

@thinsoldier My demo does not work if you remove the wrapping divs.  I think Rachel's example is definitely the way to go.

**Comment by thinsoldier** [comment]
@rachelandrew Thanks. That worked great.

<img width="396" alt="image" src="https://cloud.githubusercontent.com/assets/373834/25399461/c68b56c0-29ac-11e7-816a-d3f9f0161151.png">
