### ISSUE TITLE
Grid + SVG + %age heights seems to break

### ISSUE THREAD

**Issue by simonrrr** [rachelandrew/cssgrid-ama#63]
See https://github.com/fadedglamour/css-grid-weirdness

**Comment by rachelandrew** [comment]
Did you have a look to see if there were any logged bugs covering the issue you are seeing?

**Comment by simonrrr** [comment]
Yes indeed, nothing at all in FF, one in WebKit bugzilla that looked like it could have been related but turned out not to be. Raised bugs in both.

**Comment by rachelandrew** [comment]
Great - perhaps you could link to them. That would save me some time searching and finding them.

**Comment by rachelandrew** [comment]
I'm not really sure what response you want from me if you have identified browser bugs, but I'm happy to take a look. I'm rather time-limited however so the more info you can give is helpful.

**Comment by simonrrr** [comment]
Of course, apologies! 
WebKit
170806 – CSS Grid - row height broken by SVG

  
|  
|   |  
170806 – CSS Grid - row height broken by SVG
   |  |

  |

 

and FF
https://bugzilla.mozilla.org/show_bug.cgi?id=1356236

Best wishes

**Comment by simonrrr** [comment]
Don't worry - absolutely understood that you're time limited.
Just wanted sanity checking that these really are bugs as opposed to potential ambiguities in specs somewhere that cause differing behaviour. I know SVG plus (feature X) can occasionally behave differently across browsers.
Not a problem if you don't have time to check at all - thanks for help so far!
