### ISSUE TITLE
Trying to understand the term "space-sensitive track repetition" used in CSS Grid Layout Module

### ISSUE THREAD

**Issue by sunright** [rachelandrew/cssgrid-ama#65]
Rachel,

Thank you for you all the work you put into CSS Layout Module ( wonderful work).

Question:
What does the  "space-sensitive track repetition" in [section 2 Overview](https://www.w3.org/TR/css-grid-1/#overview) mean?

I searched the CSS Layout Module and understand can repeat track using repeat() notation.
What is the "space-sensitive" part mean? 

I appreciate any help or guidance you can provide.

Hope your enjoyed Tokyo!!

Robert DiBlasi
We all learn by sharing what we know

**Comment by rachelandrew** [comment]
Just that it is space aware, eg the `fr` unit knows how much space is available in the grid container so you don't need to do calculations.

**Comment by sunright** [comment]
Rachel,

Thank you for taking the time to answer. 

Thank you answering so quickly and help to clarify that part of CSS Grid Layout for me.  

Keep the passion for CSS Grid Layout! You are making a difference.

Robert DiBlasi
We all learn by sharing what we know
