### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by thinsoldier** [rachelandrew/cssgrid-ama#67]
I have a 3rd party widget from testimonialtree.com

In Firefox, grid cells containing this widget lose their flexiblity.
In Chrome, grid cells containing this widget become 33554400 pixels wide.

Demo: http://jsbin.com/bucelixovo/edit?html,output

If you disable `display:grid;` it shows up as expected.

You can see the widget in the bottom left of http://tinyurl.com/lsg2hfs but this is not the css grid version of the layout.

**Comment by rachelandrew** [comment]
Have you tried reproducing this as a reduced test case? What about the widget causes this behaviour?

**Comment by rachelandrew** [comment]
Closing as no test case provided.
