### ISSUE TITLE
Grid Gap Override

### ISSUE THREAD

**Issue by adamspelbring** [rachelandrew/cssgrid-ama#69]
Hey Rachel.

When setting the grid gap on the entire grid, how do you override that for specific grid template areas? For example, I have a header on row 1, and global nav on row 2, and I don't want the default gap between them. I tried using grid-gap: 0; on the specific named grid areas, but that didn't work.

Thanks so much for all that you are doing.
Adam

**Comment by thinsoldier** [comment]
Not possible at the moment but it seems many people have already been requesting it and the working group is considering it.

**Comment by rachelandrew** [comment]
You can't reset the gap on an area - if you show me the layout you are trying to achieve (in CodePen or whatever) I might be able to advise on alternate methods.

**Comment by adamspelbring** [comment]
Thanks Rachel. I basically took one of your examples and added a row track for a global menu under the header. At narrower viewports, that global menu will move down, to above the footer, and the original track will be replaced by a mobile menu row track. Eventually, I will want those menus to be flush with the header. If the gaps can't be individually adjusted, perhaps making the gaps tracks will do what I need. Your input is greatly appreciated. Here's the example at Codepen. Thanks so much. - Adam

https://codepen.io/avsdesign/pen/VbpQbG

**Comment by adamspelbring** [comment]
Thanks for the feedback thinsoldier.

**Comment by rachelandrew** [comment]
The other possibility is just to use a margin. Especially if it is a row track, just add a margin to the ones that you want a gap below.
