### ISSUE TITLE
align-items: flex-start makes parent scrollable, align-items: flex-end does not

### ISSUE THREAD

**Issue by OliverJAsh** [rachelandrew/cssgrid-ama#7]
Hi Rachel!

This is a question more related to the box alignment module than grid. Sorry if the title is obscure!

See the example at http://jsbin.com/vumuci/14/edit?html,css,output.

There are two tests in the example: one with `align-items: flex-start`, another with `align-items: flex-end`. Both tests have contents which overflow their container. I expect both to scroll due to `overflow: auto`.

The first test does scroll, but the second does not.

This behaviour is surprising to me, as it means my content is at risk of being cropped by the viewport when using flexbox/box alignment module.

--

My mental model of how this should work is the parent should grow its width to contain the contents. Upon inspection, neither of the tests seem to force the parent to grow.

I had a quick look through the flexbox spec to no avail. Hope you can help!

Olly

**Comment by rachelandrew** [comment]
So, firstly this behaves differently in grid.

I did some digging and here is a Chrome bug describing exactly this behaviour which links to a post on the CSS WG mailing list. https://bugs.chromium.org/p/chromium/issues/detail?id=503483

I'll investigate further as it seems as if this should behave the same way in both at the very least.

**Comment by OliverJAsh** [comment]
Thanks for digging through issues to find that! I believe I tested it in Firefox and saw the same behaviour, so I wonder if it is indeed a bug or as defined in the spec.

**Comment by deniscarroll** [comment]
Hi,

It seems to work if 'item' is put on the div with 'flex flex-end'. 

https://codepen.io/deniscarroll/pen/qqrEgr

Still does not solve your problem though. Well spotted OP.

Best
D

**Comment by rachelandrew** [comment]
Further on this see the discussion here: https://github.com/w3c/csswg-drafts/issues/751

**Comment by OliverJAsh** [comment]
Great, thanks Rachel!
