### ISSUE TITLE
Max width of a column using `grid-template-columns`

### ISSUE THREAD

**Issue by markhowellsmead** [rachelandrew/cssgrid-ama#71]
I’m trying to apply `grid-template-columns: 1fr minmax(1fr, 45rem)` to get two equally-sized columns, where the right column is constrained to a maximum of 45rem. Chrome tells me that this is invalid. Have I misunderstood the concept?

**Comment by rachelandrew** [comment]
You can't have a minimum of 1fr. That's invalid. You probably want to use auto.

**Comment by markhowellsmead** [comment]
Thank you for the swift response! That's solved the validity issue. I'll have to continue experimenting to get two equal-width columns though.
