### ISSUE TITLE
grid auto placement with unknown number of items

### ISSUE THREAD

**Issue by raphaelgoetter** [rachelandrew/cssgrid-ama#77]
Hello,

I try to achieve this layout : 
https://codepen.io/raphaelgoetter/pen/NjXOKb?editors=1100

But Iit's seems very tricky for an unknown number of articles:

- Negative lines (`grid-row-end: -2;`) doesn't work on implicit rows
- `grid-row: span X` needs to know the number of lines to span
- If I switch to `grid-template-areas`, all the articles will overlap instead of stacking.

Is there a solution without nesting containers ?

**Comment by PhilippeVay** [comment]
[`grid-template-rows: repeat(20, auto);`](http://codepen.io/PhilippeVay/pen/GmyeOQ?editors=1100) would solve it if there wasn't any `grid-gap` 😞 

Otherwise with a subgrid (_nesting containers_), yep it works ([example](http://codepen.io/PhilippeVay/pen/wdpOjY?editors=1100))

**Comment by rachelandrew** [comment]
Yes I don't see why you wouldn't nest a grid in this case. Is there a reason that doesn't work in your scenario?

**Comment by rachelandrew** [comment]
@PhilippeVay it's not a "subgrid" however. It is just a grid item also becoming a grid container, in the same way that a flex item can also be a flex container.

**Comment by raphaelgoetter** [comment]
> Is there a reason that doesn't work in your scenario?

Actually the only reason was the "challenge", and also because Grid could/should perhaps handle this kind of scenarios ?

My principal argument between Flexbox and Grid Layout is that the latter doesn't need nested containers... normally.

**Comment by rachelandrew** [comment]
There isn't anything wrong with nesting containers, in fact in the real world, semantics often dictate nesting of elements. However I'd be interested in real use case scenarios certainly.
