### ISSUE TITLE
Fr units and overflow-scroll in Safari. Bug?

### ISSUE THREAD

**Issue by mrmurphy** [rachelandrew/cssgrid-ama#78]
Hi, Rachel, thanks for taking the time to answer questions!

I switched to CSS grid specifically because I needed to be able to have an element fill all of its available space, without knowing beforehand dimensions for that space, and then scroll any content that doesn't fit. Using `overflow: scroll` on a grid area that has a height of N `fr` units does the trick very nicely in Chrome and Firefox, but in safari the content just flows right out of the box and down the page.

Here's a simple reproducible example:
https://codepen.io/murphyrandle/pen/OmQMxY

Does this look like a bug to do? Or am I just using the spec incorrectly? If it is a bug, how should I go about filing it? I've never filed a WebKit bug before. And in the mean-time can you think of any workarounds?

**Comment by mrmurphy** [comment]
Nevermind, I'll close this one myself. I went to open an issue on WebKit's bug tracker, but discovered that the problem is fixed in Safari Technical Preview. So I guess it was a bug, and that it's now fixed!

**Comment by adamwoodnz** [comment]
Hi @splodingsocks could you please link to the webkit issue or technical preview release notes?

**Comment by adamwoodnz** [comment]
I've forked your pen and changed it to demonstrate the bug in horizontal format: 

https://codepen.io/pixelantics/pen/jwbymp

This displays as expected in Chrome, Edge and even IE11, but not Safari or Firefox :(

Keen to find out if the issue has been fixed.

**Comment by mrmurphy** [comment]
Hi, @adamwoodnz, looks like the vertical one isn't a problem in FF, but the horizontal one is. If you find or file a bug for that please link it here.

I didn't find an issue, or release notes for Safari Technology Preview, I just downloaded it, installed, and tested, and it worked. Sorry I don't have a link for you!

**Comment by mrmurphy** [comment]
Good news is, in STP the horizontal version works as well: 
![image](https://user-images.githubusercontent.com/1227109/26903510-c489a3da-4b9a-11e7-834d-777c23ac9848.png)

So just FF is lacking there.

**Comment by adamwoodnz** [comment]
ok thanks, I'll try that
