### ISSUE TITLE
Can a grid area consist of one cell?

### ISSUE THREAD

**Issue by sunright** [rachelandrew/cssgrid-ama#79]
Rachel,

Can a grid area consist of one cell?

[Spec says](https://www.w3.org/TR/css-grid-1/#grid-area):
A grid area consists of one or more adjecent grid cells.

The spec seem to be saying ( at least to me) the smallest grid area consist of at least two cells or more?
So there is no such thing as a grid area consisting of one single cell?

Thank for offering to help,with questions about the grid and grid spec.

Robert DiBlasi
We all learn by sharing what we know

**Comment by rachelandrew** [comment]
"One **or** more adjacent cells", so yes one is acceptable.

**Comment by sunright** [comment]
Rachel,

Interesting. Thank you for your answer :-)

I am glad you agree there can be one cell grid area.
But I still read that sentence to mean something very different.
I wish it said:
> A grid area can contain one cell or can contain multiple adjacent grid cells. 

I still feel the spec seems not to be clear on grid areas containing only one cell.

Here is another example in the spec where the spec seems imply a grid area must contain more than one cell.
[Section 9](https://www.w3.org/TR/css3-grid-layout/#placement): Placing Grid Items:
`Every grid item has a "grid area", a rectangular set of grid cells that the grid item occupies`

If you agree that a grid area can contain one cell, i feel this sentence might need to be adjusted in the spec?

I would suggest the correction be something like:

> Every grid item has a grid area, a rectangular region of one grid cell or multiple adjacent cells that the grid item occupies.

I read the w3c specs very closely. I take the non-normative sections of the spec to be just as important as the normative. I just want the w3c Specs to be clear as possible so everyone can learn from the source

So just confirm , you believe a grid area can contain just one cell?

I really do appreciate the effort you are putting into the CSS Grid Layout module to make it real.
You have made a positive impact on the web.

Thank you again,

Robert DiBlasi
We all learn by sharing what we know

**Comment by rachelandrew** [comment]
What problem is this causing you?

**Comment by sunright** [comment]
Thank you again for responding.

You asked - What problem is this causing?

I have sent notes to W3C github page for CSS Grid Layout. But the editors have not responded to my techical questions or editorial comments (I understand) - editorial comment and general nit picking about missing periods is low on the list to respond to and most of the time done once the spec is updated. 

It just makes it hard to find the answer if they do not choose to respond.

I enjoy reading w3c technical writing -yes I am that kind of person :-)
If I find something that does not make sense to me, I like to help out. I do not know if it is me that does not understand the sentence or concept or there is something inconsistent or wrong with the writing. 

So you have so graciously offered to possibly answer questions that have to do with the CSS Grid Layout Module, I thought I'd ask you if I found something possibly wrong or an act clear in the spec.

I am a very visual person and I have been drawing out the spec. I'm finding some of the wording it's not consistent. So the problem it's causing me general confusion about a few definition in the spec (I don't think you can help me with that:-) but I thought I give a try.


It is hard to find individuals of your caliber, who are willing take the time possibly answer such simple questions of a technical nature about the CSS Grid Layout Module.

Please forgive me if this not the form for these type of questions (I tried to form a question for you to answer as your requested).

If you know of an active form for discussing CSS Grid Layout, I would love to be a part of it.

Again, thank you for keeping the web a kind place.

Robert DiBlasi
We all learn by sharing what we know

**Comment by rachelandrew** [comment]
One or more adjacent cells seems clear to me, however the purpose of this AMA isn't to bikeshed spec issues.

If you believe there is a specification issue then the CSS WG repo is the place to post it. No, you most likely won't get an immediate answer, as the editors have many other specifications to look at too. So you will have to be patient.
