### ISSUE TITLE
grid-gap problem with borders

### ISSUE THREAD

**Issue by kirabug** [rachelandrew/cssgrid-ama#81]
I'm working on converting some form field components into CSS Grid so that they're easier to handle with error message layout, etc. 

In a number of cases today we use absolute positioning to place icons in the form field area, and I'd rather use Grid for both a) better semantics and b) nicer displays. 

The problem I'm having is this: for some reason, even with grid-gap set to 0 the gaps aren't actually closed some of the time, which is leaving white gaps in my form fields. 

Example codepen: https://codepen.io/kirabug/pen/PmBRJw/

The part that's driving me crazy is that on the right side, where the Cancel button is located, the borders meet seamlessly. But on the left side, where the Search icon is located, there's a gap, and if I remove either of the borders that separate the Filter button from the Search icon a gap opens there too. I've tried making various things both smaller and larger with no luck. 

Problem exists in Safari 10.1, Firefox 53.0 and Chrome 58.0 and I'm stumped. I can't tell if I'm a moron or if grid-gap isn't working correctly (or both, both is always an option). 

Any thoughts?
![firefox css grid border problem](https://cloud.githubusercontent.com/assets/28521009/26124359/295504a4-3a4c-11e7-8117-831a5252d65e.png)

**Comment by webcraftsman** [comment]
@kirabug If you take out the justify-self:start declaration on .grid-searchicon, the gaps go away. You really don't need that declaration (or align-self: start either). The justify-self is the culprit. I would suggest watching Rachel's tutorial on aligning and justifying the grid to better understand what those properties do. [http://gridbyexample.com/video/align-grid/](http://gridbyexample.com/video/align-grid/)

**Comment by rachelandrew** [comment]
Please create a reduced test case that shows just the problem you have.

**Comment by kirabug** [comment]
@webcraftsman nailed it - apparently justify-self: start and align-self: start were causing the problem. thanks to both of you @webcraftsman and @rachelandrew!
