### ISSUE TITLE
Is it possible to smoothly animate between different layouts?

### ISSUE THREAD

**Issue by ariesshrimp** [rachelandrew/cssgrid-ama#82]
I see that [the `grid-template-columns` property is not listed as animatable on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties). And yet I feel like it should be possible...

[Example Codepen](https://codepen.io/joseph_fraley/pen/ybQyVX)
![GIF shows transitions snapping rather than animating](http://g.recordit.co/u6V6og4FvH.gif)

```html
<style>
#grid {
  display: grid;
  height: 100vh;
  transition: all 2s;
}
  
#one { background: blue; }
#two { background: red; }

.two-column {  grid-template-columns: 20% 80%;}
.one-column {  grid-template-columns: 0% 100%;}
</style>


<script>
function swap() {
  	const grid =
      document.getElementById('grid') 
    
    grid.className = 
      grid.className === 'one-column' 
        ? 'two-column' 
        : 'one-column'
	}
</script>


<div id="grid" class="two-column">
  <div id="one">COLUMN ONE</div>
  <div id="two">COLUMN TWO</div>
</div>

<button onClick="swap()">Switch Layouts<button>
```

**Comment by rachelandrew** [comment]
The spec says that you can animate the track listing and gaps. However whether browsers have implemented this is another matter. There are a number of Issues asking the exact same question here - I suggest you all raise them with browsers :)

**Comment by xlf1024** [comment]
@joefraley I heared FF now supports animating CSS grid as of today ( https://airtable.com/shrApCP9xiD6icXKe/tblGkcgBmkELvBNzR ). Haven't updated yet, though.

**Comment by webcraftsman** [comment]
@xlf1024 It is Firefox Nightly that now supports animating CSS grids. It is a separate install from regular Firefox and allows you to play with features that will be implemented in Firefox in the future.

https://codepen.io/rachelandrew/details/BvMMmZ

**Comment by xlf1024** [comment]
@webcraftsman oh, right, I misunderstood the date in the backlog. Grid animation support is scheduled for FF66 according to their backlog, and I misinterpreted the date next to the version number in the backlog. Maybe it's the beta today?
