### ISSUE TITLE
Responsive 2 column layout

### ISSUE THREAD

**Issue by fidlerryan** [rachelandrew/cssgrid-ama#83]
I have defined my grid as follows:

selector{
	display: grid;
	grid-template-columns: repeat(auto-fit, minmax(49.5%, 1fr));
	grid-gap: 1%;
}

However, the child divs within the selector parent do not automatically collapse to 1 column on narrow viewports unless an explicit pixel-based width is used as the first parameter in minmax. Why is this?

**Comment by rachelandrew** [comment]
because you have set a minimum of 49.5% so it will always be a minimum of 49.5%.

**Comment by fidlerryan** [comment]
Using grid layout, is there a way to specify single full-width column on narrow viewports, and 2 equal-width columns on wider viewports, without using media queries?

**Comment by rachelandrew** [comment]
yes. Use a pixel width as your minimum and 1fr as your max (as you already identified).

**Comment by fidlerryan** [comment]
Okay. Thank you for your gridbyexample.com online resource and _Get Ready for CSS Grid Layout_ brief.
