### ISSUE TITLE
Reduced Test Case of Firefox bug involving nested grids and input type=text tags

### ISSUE THREAD

**Issue by thinsoldier** [rachelandrew/cssgrid-ama#84]
https://jsfiddle.net/Lw3gpdak/2/

Problem also happens with type=number.

Off-topic: how should text inputs behave by default when no min/max/width is specified for them and they are the children of a multi-column grid? Divs and spans seem to always stretch to width of the column by default which makes the most sense in my opinion but input elements do not.

**Comment by rayfoss** [comment]
his example works in my browser... but I still have the issue and I can't isolate the case. i do have a nested grid with a media tag.

![weird input field](https://user-images.githubusercontent.com/876076/30600265-9889dce2-9d24-11e7-8147-1661c49a72d4.gif)

**Comment by thinsoldier** [comment]
I just noticed that this problem doesn't happen in Firefox anymore.
