### ISSUE TITLE
CSS grid with variable-height content

### ISSUE THREAD

**Issue by Ollie-w** [rachelandrew/cssgrid-ama#86]
![www duetshop co uk-temp-productdetail asp-productid nuvo-nsf title nuvo-nsf1-plastic-student-flute-outfit 1](https://user-images.githubusercontent.com/14265345/27039396-bfbc9bf2-4f85-11e7-96fa-24549cc783cc.png)
![www duetshop co uk-temp-productdetail asp-productid nuvo-nsf title nuvo-nsf1-plastic-student-flute-outfit 2](https://user-images.githubusercontent.com/14265345/27039403-c4620278-4f85-11e7-97bf-ba9c69dc94b6.png)
I have an element on my page that can grow and collapse in size. It is a direct child of my grid. I'm getting loads of white-space below my footer when it collapses. 

  ```
    display: grid;
    grid-auto-flow: dense;
    grid-template-columns: 5fr 4fr;
```

My body and html elements have no margin or padding. The whitespace is below the body and html element :s

**Comment by rachelandrew** [comment]
Please create a reduced test case of the issue. I'm afraid time doesn't allow me to debug layouts for everyone, but if you can isolate the issue in a CodePen I'm happy to take a look.

**Comment by Ollie-w** [comment]
I appreciate you not wanting to look through a mass of code to debug, but if I phrase the question as a general one maybe you have a suggestion: 

- A grid-row is sized according to the content 
- The page has expandable content
- The content of the expandable region is dynamic - so you can't know ahead of time how tall it would be when expanded.

**Comment by thinsoldier** [comment]
@Ollie-w 

> I'm getting loads of white-space below my footer when it collapses.

So what you want is a _sticky footer_ ?

**Comment by rachelandrew** [comment]
closed as poster didn't want to provide a reduced test case.
