### ISSUE TITLE
Recreating jQuery Masonry using CSS Grid

### ISSUE THREAD

**Issue by powerbuoy** [rachelandrew/cssgrid-ama#89]
I haven't really gotten started with CSS grid yet but have read a few tutorials and looked at some examples.

One thing that isn't clear to me still though is whether it is possible to recreate the "masonry" layout jQuery plugins like Masonry and Isotope achieve?

I know it's already possible using `column-count` but that rearranges the order of the grid items.

In case you're not familiar with masonry it allows arranging items of different widths and heights into a grid with equal gutter. I think it's easiest to look at the demo page: https://masonry.desandro.com/v2/demos/basic-multi-column.html

So my question is; is it possible to achieve with CSS grid?

Thanks!

**Comment by rachelandrew** [comment]
see the discussion here https://github.com/rachelandrew/cssgrid-ama/issues/19

**Comment by powerbuoy** [comment]
Sorry, should've checked closed issues. Thanks!
