### ISSUE TITLE
What are the differences between new implementations and the 2011 one from Internet Explorer?

### ISSUE THREAD

**Issue by rik** [rachelandrew/cssgrid-ama#9]
With Blink and Gecko implementations shipping early 2017, with WebKit implementation probably shipping in the fall 2017, it seems the 4 major web engines will support grids.

Is the 2011 Internet Explorer implementation supporting the same feature set? And will it be possible to just convert the 2016 syntax into 2011 syntax with something like Autoprefixer?

**Comment by rachelandrew** [comment]
The answer to both of those questions is no. However in terms of whether we will be able to usefully use the old syntax for backwards compatibility, the answer is it depends.

I used a lot of words to explain why in a blog post https://rachelandrew.co.uk/archives/2016/11/26/should-i-try-to-use-the-ie-implementation-of-css-grid-layout/

**Comment by rik** [comment]
Question answered! (and with greater details than I expected, thanks a lot)
