### ISSUE TITLE
Multiple grids on one page

### ISSUE THREAD

**Issue by brianran** [rachelandrew/cssgrid-ama#90]
Hi I thank you for all your examples.
I am starting to rewriting my www.randallfamilyhistory.com  Site 50 plus pages in css grid.
I would like to see an example of using more than one grid in CSS Grid.
Say standard grid plus applying say a minmax() to 2 selectors. I have found out that using a class is the way, but an example would help.

**Comment by rachelandrew** [comment]
There is no reason to not have multiple grids on a page. I would need to see a code example to be able to help further, please post something to CodePen.

**Comment by thinsoldier** [comment]
@brianran Here are some examples

http://www.bfsb-bahamas.com/bahamaslandfall/2017/brazil/GRID/#form  
There is a grid for the upper half where the photo is, another grid containing the overall form, and a 3rd grid only containing the form text fields.

http://thinsoldier.com/wip/nike-grid/  
This one uses a grid for the overall layout and another just for the form area.

You should check out the Grid Inspection Tools in Firefox: https://hacks.mozilla.org/2017/06/new-css-grid-layout-panel-in-firefox-nightly/

**Comment by brianran** [comment]
Many Thanks for your very good examples. I will proceed to try out.
I already use the grid inspection tool.
You are very generous with help

**Comment by thinsoldier** [comment]
@brianran Currently updating the first example to be responsive.

**Comment by brianran** [comment]
Many thanks I managed to incorporate into my Web Site, and worked but it did not meet my requirements so are using just normal grid
