### ISSUE TITLE
Figure Element adding space in CSS Grid?

### ISSUE THREAD

**Issue by joshrcraig** [rachelandrew/cssgrid-ama#91]
Rachel,
I'm creating some pages for my students to work with and I'm running into a problem with the Figure element seeming to add space around itself in my CSS Grid. Please see the first image. (This may not be specific to CSS Grid, I just haven't had an issue with it until I've used figure in a CSS Grid). 

If I change the element from a Figure to a Section the element occupies all of the space around it (See the 2nd image).

The area in question is the same grid-area ("fig2"), one with the element being used as a figure in the first image vs. section in the second. Do you know if Figure must be nested within another element or does it inherently add padding around itself? Any suggestions?

Thanks in advance and thanks for all you do!

![figure](https://user-images.githubusercontent.com/17983809/27925516-fd51c764-6252-11e7-87e7-78919cd390d6.PNG)
![section](https://user-images.githubusercontent.com/17983809/27925517-ff14094a-6252-11e7-9d9a-340e8f39bde1.PNG)

**Comment by webcraftsman** [comment]
@joshrcraig Do you account for the default browser margin of 16px 40px on the figure element? Even normalize will set a margin on the figure element. I have to remember that on almost every project.

**Comment by joshrcraig** [comment]
If I set the figure element to have a margin of '0" then it does seem to get rid of the space - so thank you for the idea. It's just strange I have to specify the margin for the figure element individually because I have the body margin set to "0" and the element above and below in both images don't seem to have this additional space (nav, main above and then footer below) and I didn't individually specify their margins to be zero...

**Comment by rachelandrew** [comment]
If you inspect the element using DevTools then you can see what is being applied. I don't think this is a grid question.

If you have a grid question in future please post a code example, as a reduced test case. I can't tell you a lot from a picture of a website. The Readme explains this.
