### ISSUE TITLE
Fallback for Multi-Column and Multi-Row Grid

### ISSUE THREAD

**Issue by davezeli** [rachelandrew/cssgrid-ama#92]
Hello Rachel,

I read your latest articles about CSS Grid and fallbacks and that's exactly a topic we were discussing at work lately. We developed a new grid layout based on CSS Grid. We even used the older syntax for IE and it worked great. But of course that didn't worked on older Chrome/Firefox/Safari browsers and some mobile versions had also trouble. Anyway, we decided to create that layout with bootstrap (again) because we knew it will work even on older and newer browsers.

That doesn't mean that the idea of using CSS Grid is completely dropped. I think some components can be created by CSS Grid and fallbacks for older browsers with very little code. 

So, here is something I wanted to create with CSS Grid and a good fallback for browser support.

![layout-example](https://user-images.githubusercontent.com/27484312/27988996-a9dbb5fc-642f-11e7-98c5-49827c834442.jpg)

Those boxes should later contain images (as img tags) and text.

The CSS Grid part was easy :) and for the fallback I used column-count because I read in one of your articles, that this approach could be a good fallback solution.

Here is my jsfiddle: https://jsfiddle.net/kz7w40q9/

Maybe you can tell me if column-count is a good solution for a CSS Grid fallback in this situation or if there are better solutions? For example, If I change the height for box3 from 200px to 100px the boxes would be splitted into multiple columns. (I think as long as the height is fixed, that is no problem). But I also noticed that column-width doesn't work. If I apply it, the height doesn't work anymore - but I probably did something wrong.

To test the fallback, I used feature queries to enable/disable grid support. It's disabled at first.

Of course, that layout could be done with bootstrap again but inspired by your articles I wanted to try something new and if it works... ;-)

All the best,
David

**Comment by rachelandrew** [comment]
I'm not sure what the question really is here? Your fallback layout should be something that works for browsers that don't support grid and that you are happy with. There isn't a right or wrong that I can declare.

If you have a specific question then get it into a simple test case that I can look at.
