### ISSUE TITLE
Setting fixed row height with repeat and auto-fill 

### ISSUE THREAD

**Issue by marisadi** [rachelandrew/cssgrid-ama#94]
Hi Rachel

I've been experimenting with setting a fixed height and/or max-height on rows with repeating patterns with and without an initial header row with an alternate height - much like in your [article](https://rachelandrew.co.uk/archives/2015/02/04/css-grid-layout-creating-complex-grids/):

`grid-template-rows: auto repeat(5, 100px);`
> For the rows I have created a single row with a height of auto to place the header in and then a repeating pattern of five 100 pixels rows.

But I want to do this:
`grid-template-rows: auto repeat(auto-fill, 100px);`
or
`grid-template-rows: auto repeat(auto-fill, minmax(100px, 300px));`

Here are my codepens:
[Height changes on first row only](https://codepen.io/marisaofworld/pen/ayoOGY)
[Bottom row disappears](https://codepen.io/marisaofworld/pen/KvPpEW?editors=1100#)

Any help is appreciated. 

Thank you!

**Comment by rachelandrew** [comment]
If you want rows to just have a certain height then you can use `grid-auto-rows: 100px` which would make 100 pixel tall rows, or `grid-auto-rows: minmax(100px, auto);` which would give you rows with a minimum height of 100 pixels and a max of auto, this accommodating the content without overflows.
