### ISSUE TITLE
Testing Grid CSS at large number of columns accross browsers

### ISSUE THREAD

**Issue by Ponant** [rachelandrew/cssgrid-ama#96]
Do the specs or the browsers limit the total number of columns? Is performance affected for the same html and css file sizes?
A small test brings in some strange behaviour depending on the browser (Chrome, FF, Brave)
**CSS**
```
 * {
            box-sizing: border-box;
        }
        .grid {
            display: grid;
            border: 1px solid black;
            grid-template-columns: repeat(N, 1fr);
        }

        .p1 {
            grid-column: 1/-1;
            background-color: #ff6a00;
        }
```
**HTML**
```
    <div class="grid">
        <div class="p1">.</div>
    </div>
```
where N is any integer that we may set. 

**Expected**
div p1 will occupy the whole grid.
**Result**
Starting at N=400 the p1 div does not fill the whole grid and the resulting artificial gap on the right varies as the browser gets resized. Furthermore, this gap is not a monotonic function of the browser's size.

**Comment by Ponant** [comment]
It seems to be a bug or a limitation, @rachelandrew ?
https://codepen.io/anon/pen/RZWjbx

**Comment by rachelandrew** [comment]
As specced browsers can clamp the grid at a certain number of tracks.

https://www.w3.org/TR/css-grid-1/#overlarge-grids
