### ISSUE TITLE
How to make grid-auto-rows work in Firefox?

### ISSUE THREAD

**Issue by Ponant** [rachelandrew/cssgrid-ama#97]
I am following @rachelandrew's video on stacking and z-index https://gridbyexample.com/video/stacking-and-z-index/ and the firefox inspector tells me that
`            grid-auto-rows: 90px minmax(200px, auto);`
is not a valid property.
codepen here 
https://codepen.io/anon/pen/vJNBWm
The css is properly applied in chrome and brave.
Is that a known issue or am I missing something?

**Comment by rachelandrew** [comment]
It's a Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1339672

grid-auto-rows should be able to take a track listing.
