### ISSUE TITLE
Why justify-items or justify-content brings items out of the grid?

### ISSUE THREAD

**Issue by Ponant** [rachelandrew/cssgrid-ama#99]
When we squeeze the width of the browser the log in and register anchor tags below get out of the grid in Firefox 54.0.1. I surely do not expect this from a grid, is that a bug?
https://codepen.io/anon/pen/vJKKNX

**Comment by rachelandrew** [comment]
What do you mean by "get out of the grid?"

You have fixed width column tracks so they won't shrink down. If you want that to happen use an `fr` unit instead. At small sizes you might want to use a media query to rearrange the items.

**Comment by Ponant** [comment]
I am using media queries elsewhere. By out I mean the items are found outside the grid's red border. I am expecting the grid's red border to always surround the tracks.

**Comment by rachelandrew** [comment]
Your grid doesn't have a size set on it, so the fixed size of the tracks means they are breaking out of the grid - this seems consistent across browsers. If you really want to fix the size like that I would suggest adding a fixed size to the grid container as well.
